services:
  dockercompose:
    image: dockercompose
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:3000

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockercompose
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
